-d D:\repos\LUTRAM_Stress_Test\3.build\hw_build_GUI\impl\gwsynthesis\hw_build_GUI.vg
-p GW2AR-18C-QFN88P-8
-pn GW2AR-LV18QN88PC8/I7
-cst D:\repos\LUTRAM_Stress_Test\1.hw\constraints\top.pinout.cst
-cfg D:\repos\LUTRAM_Stress_Test\3.build\hw_build_GUI\impl\pnr\device.cfg
-sdc D:\repos\LUTRAM_Stress_Test\1.hw\constraints\top.timing.sdc
-bit
-tr
-ph
-timing
-cst_error
-place_option 1
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
